# Japanese translation of glib-networking message catalog.
# Copyright (C) 2011-2012, 2015, 2020 Free Software Foundation, Inc.
# This file is distributed under the same license as glib-networking package.
# Takayuki KUSANO <AE5T-KSN@asahi-net.or.jp>, 2011-2012.
# Hideki Yamane <henrich@debian.org>, 2011-2012.
# Yoji TOYODA <bsyamato@sea.plala.or.jp>, 2012.
# Jiro Matsuzawa <jmatsuzawa@gnome.org>, 2015.
# sicklylife <translation@sicklylife.jp>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: glib-networking master\n"
"Report-Msgid-Bugs-To: https://gitlab.gnome.org/GNOME/glib-networking/issues\n"
"POT-Creation-Date: 2020-01-31 14:56+0000\n"
"PO-Revision-Date: 2020-02-12 00:00+0900\n"
"Last-Translator: sicklylife <translation@sicklylife.jp>\n"
"Language-Team: Japanese <gnome-translation@gnome.gr.jp>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: proxy/libproxy/glibproxyresolver.c:159
msgid "Proxy resolver internal error."
msgstr "プロキシリゾルバーでの内部エラーです。"

#: tls/base/gtlsconnection-base.c:538 tls/base/gtlsinputstream.c:78
#: tls/base/gtlsinputstream.c:141 tls/base/gtlsoutputstream.c:78
#: tls/base/gtlsoutputstream.c:143
msgid "Connection is closed"
msgstr "コネクションが切断されています"

#. Cannot perform a blocking operation during a handshake on the
#. * same thread that triggered the handshake. The only way this can
#. * occur is if the application is doing something weird in its
#. * accept-certificate callback. Allowing a blocking op would stall
#. * the handshake (forever, if there's no timeout). Even a close
#. * op would deadlock here.
#.
#: tls/base/gtlsconnection-base.c:612
msgid "Cannot perform blocking operation during TLS handshake"
msgstr ""

#: tls/base/gtlsconnection-base.c:677 tls/base/gtlsconnection-base.c:1219
msgid "Socket I/O timed out"
msgstr "ソケット I/O がタイムアウトしました"

#: tls/base/gtlsconnection-base.c:845
msgid "Server required TLS certificate"
msgstr "サーバーが TLS 証明書を要求しました"

#: tls/base/gtlsconnection-base.c:1451
msgid "Peer does not support safe renegotiation"
msgstr ""

#: tls/base/gtlsconnection-base.c:1586 tls/gnutls/gtlsconnection-gnutls.c:347
#: tls/openssl/gtlsconnection-openssl.c:184
#, c-format
msgid "Unacceptable TLS certificate"
msgstr "受け付けられない TLS 証明書です"

#: tls/base/gtlsconnection-base.c:2051
#, c-format
msgid "Receive flags are not supported"
msgstr ""

#: tls/base/gtlsconnection-base.c:2203
#, c-format
msgid "Send flags are not supported"
msgstr ""

#: tls/gnutls/gtlscertificate-gnutls.c:178
#: tls/openssl/gtlscertificate-openssl.c:170
#, c-format
msgid "Could not parse DER certificate: %s"
msgstr "DER 形式の証明書を解析できませんでした: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:199
#: tls/openssl/gtlscertificate-openssl.c:190
#, c-format
msgid "Could not parse PEM certificate: %s"
msgstr "PEM 形式の証明書を解析できませんでした: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:230
#: tls/openssl/gtlscertificate-openssl.c:209
#, c-format
msgid "Could not parse DER private key: %s"
msgstr "DER 形式の秘密鍵を解析できませんでした: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:261
#: tls/openssl/gtlscertificate-openssl.c:228
#, c-format
msgid "Could not parse PEM private key: %s"
msgstr "PEM 形式の秘密鍵を解析できませんでした: %s"

#: tls/gnutls/gtlscertificate-gnutls.c:297
#: tls/openssl/gtlscertificate-openssl.c:263
msgid "No certificate data provided"
msgstr "証明書のデータが与えられていません"

#: tls/gnutls/gtlsconnection-gnutls.c:139
#: tls/gnutls/gtlsconnection-gnutls.c:157
#: tls/openssl/gtlsclientconnection-openssl.c:408
#: tls/openssl/gtlsserverconnection-openssl.c:463
#, c-format
msgid "Could not create TLS connection: %s"
msgstr "TLS コネクションを確立できませんでした: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:291
#: tls/gnutls/gtlsconnection-gnutls.c:302
#: tls/gnutls/gtlsconnection-gnutls.c:316
#: tls/openssl/gtlsconnection-openssl.c:151
#, c-format
msgid "Peer failed to perform TLS handshake: %s"
msgstr "通信相手が TLS ハンドシェイクの実行に失敗しました: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:324
msgid "TLS connection closed unexpectedly"
msgstr "TLS コネクションが突然閉じられました"

#: tls/gnutls/gtlsconnection-gnutls.c:339
#: tls/openssl/gtlsconnection-openssl.c:176
msgid "TLS connection peer did not send a certificate"
msgstr "TLS の通信相手が証明書を送信しませんでした"

#: tls/gnutls/gtlsconnection-gnutls.c:355
#, c-format
msgid "Peer sent fatal TLS alert: %s"
msgstr ""

#: tls/gnutls/gtlsconnection-gnutls.c:365
msgid "Protocol version downgrade attack detected"
msgstr "プロトコルバージョンのダウングレード攻撃を検出しました"

#: tls/gnutls/gtlsconnection-gnutls.c:374
#, c-format
msgid "Message is too large for DTLS connection; maximum is %u byte"
msgid_plural "Message is too large for DTLS connection; maximum is %u bytes"
msgstr[0] ""

#: tls/gnutls/gtlsconnection-gnutls.c:383
msgid "The operation timed out"
msgstr "操作がタイムアウトしました"

#: tls/gnutls/gtlsconnection-gnutls.c:715
#, c-format
msgid "Error performing TLS handshake: %s"
msgstr "TLS ハンドシェイク実行中にエラーが発生しました: %s"

#: tls/gnutls/gtlsconnection-gnutls.c:818
#: tls/openssl/gtlsconnection-openssl.c:252
#: tls/openssl/gtlsconnection-openssl.c:302
msgid "Error performing TLS handshake"
msgstr "TLS ハンドシェイク実行中にエラーが発生しました"

#: tls/gnutls/gtlsconnection-gnutls.c:864
#: tls/gnutls/gtlsconnection-gnutls.c:924
#: tls/openssl/gtlsconnection-openssl.c:409
msgid "Error reading data from TLS socket"
msgstr "TLS ソケットからのデータ読み込み中にエラーが発生しました"

#. flags
#: tls/gnutls/gtlsconnection-gnutls.c:946
#: tls/gnutls/gtlsconnection-gnutls.c:1010
#: tls/openssl/gtlsconnection-openssl.c:453
msgid "Error writing data to TLS socket"
msgstr "TLS ソケットへのデータ書き込み中にエラーが発生しました"

#: tls/gnutls/gtlsconnection-gnutls.c:980
#, c-format
msgid "Message of size %lu byte is too large for DTLS connection"
msgid_plural "Message of size %lu bytes is too large for DTLS connection"
msgstr[0] ""

#: tls/gnutls/gtlsconnection-gnutls.c:982
#, c-format
msgid "(maximum is %u byte)"
msgid_plural "(maximum is %u bytes)"
msgstr[0] "(%u バイトが最大値)"

#: tls/gnutls/gtlsconnection-gnutls.c:1029
#, c-format
msgid "Error performing TLS close: %s"
msgstr "TLS クローズ実行中にエラーが発生しました: %s"

#: tls/gnutls/gtlsdatabase-gnutls.c:553
msgid ""
"Failed to load system trust store: GnuTLS was not configured with a system "
"trust"
msgstr ""

#: tls/gnutls/gtlsdatabase-gnutls.c:558 tls/openssl/gtlsdatabase-openssl.c:187
#, c-format
msgid "Failed to load system trust store: %s"
msgstr ""

#: tls/gnutls/gtlsserverconnection-gnutls.c:122
#: tls/openssl/gtlsserverconnection-openssl.c:172
#: tls/openssl/gtlsserverconnection-openssl.c:226
msgid "Certificate has no private key"
msgstr "証明書に秘密鍵がありません"

#: tls/openssl/gtlsclientconnection-openssl.c:306
#: tls/openssl/gtlsclientconnection-openssl.c:357
#: tls/openssl/gtlsserverconnection-openssl.c:345
#: tls/openssl/gtlsserverconnection-openssl.c:396
#, c-format
msgid "Could not create TLS context: %s"
msgstr "TLS コンテキストを作成できませんでした: %s"

#: tls/openssl/gtlsconnection-openssl.c:192
#, c-format
msgid "Unacceptable TLS certificate authority"
msgstr "受け付けられない TLS 認証局です"

#: tls/openssl/gtlsconnection-openssl.c:200
msgid "Digest too big for RSA key"
msgstr ""

#: tls/openssl/gtlsconnection-openssl.c:490
msgid "Error performing TLS close"
msgstr "TLS クローズ実行中にエラーが発生しました"

#: tls/openssl/gtlsdatabase-openssl.c:227
msgid "Could not create CA store"
msgstr ""

#: tls/openssl/gtlsfiledatabase-openssl.c:454
#, c-format
msgid "Failed to load file path: %s"
msgstr "ファイルパスの読み込みに失敗しました: %s"

#: tls/openssl/gtlsserverconnection-openssl.c:179
#: tls/openssl/gtlsserverconnection-openssl.c:245
#, c-format
msgid "There is a problem with the certificate private key: %s"
msgstr "証明書の秘密鍵に問題があります: %s"

#: tls/openssl/gtlsserverconnection-openssl.c:188
#: tls/openssl/gtlsserverconnection-openssl.c:237
#, c-format
msgid "There is a problem with the certificate: %s"
msgstr "証明書に問題があります: %s"

#~ msgid "Could not import PKCS #11 certificate URI: %s"
#~ msgstr "PKCS #11 証明書の URI をインポートできませんでした: %s"

#~ msgid "Operation would block"
#~ msgstr "操作がブロックされます"

#~ msgid "Peer requested illegal TLS rehandshake"
#~ msgstr "通信相手が不当な TLS の再ハンドシェイクを要求しました"

#~ msgid "Server did not return a valid TLS certificate"
#~ msgstr "サーバーが有効な TLS 証明書を返しませんでした。"

#~ msgid ""
#~ "This is the last chance to enter the PIN correctly before the token is "
#~ "locked."
#~ msgstr ""
#~ "これがトークンがロックされる前に正しく PIN コードを入力する最後のチャンス"
#~ "です。"

#~ msgid ""
#~ "Several PIN attempts have been incorrect, and the token will be locked "
#~ "after further failures."
#~ msgstr ""
#~ "正しくない PIN コードの入力が複数回行われたので、さらに失敗するとトークン"
#~ "はロックされます。"

#~ msgid "The PIN entered is incorrect."
#~ msgstr "入力された PIN コードが正しくありません。"

#~ msgid "Module"
#~ msgstr "モジュール"

#~ msgid "PKCS#11 Module Pointer"
#~ msgstr "PKCS#11 モジュールポインター"

#~ msgid "Slot ID"
#~ msgstr "スロット ID"

#~ msgid "PKCS#11 Slot Identifier"
#~ msgstr "PKCS#11 スロット ID"
